Reason: updates

diff --git a/main b/main
--- a/main
+++ b/main
@@ -2,6 +2,7 @@
 #PBS -l nodes=1:ppn=8,vmem=30gb,walltime=8:00:00
 #PBS -N app-trekker-roi-tracking
 
+
 [ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
 echo $FREESURFER_LICENSE > license.txt
 
@@ -18,8 +19,25 @@ fi
 #echo "reslicing rois"
 time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./resliceROI.sh $DIFF
 
-time singularity exec -e docker://brainlife/trekker:0.4 ./run.sh
+if [ ! -f csf_bin.nii.gz ]; then
+	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./preprocess.sh
+fi
 
-time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator
+time singularity exec -e docker://brainlife/trekker:0.5 ./tracking.py
 
-mv *track_* track*.json track*.vtk track*.tck ./raw/
+if [ ! -f ./track/track.tck ]; then
+	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh
+fi
+
+if [ ! -f ./wmc/classification.mat ]; then
+	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator
+fi
+
+if [ -f ./wmc/classification.mat ]; then
+	mv *track*.txt track*.tck ./raw/
+	echo "complete"
+	exit 0
+else
+	echo "tracking failed"
+	exit 1
+fi
