reason: fix issues

diff --git a/main b/main
--- a/main
+++ b/main
@@ -28,16 +28,16 @@ time singularity exec -e docker://brainlife/trekker:0.6 ./tracking.py
 if [ ! -f ./track/track.tck ]; then
 	time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh
 fi
-
-if [ ! -f ./wmc/classification.mat ]; then
-	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator
-fi
-
-if [ -f ./wmc/classification.mat ]; then
-	mv *track*.txt track*.tck ./raw/
-	echo "complete"
-	exit 0
-else
-	echo "tracking failed"
-	exit 1
-fi
+#
+#if [ ! -f ./wmc/classification.mat ]; then
+#	time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/classificationGenerator
+#fi
+#
+#if [ -f ./wmc/classification.mat ]; then
+#	mv *track*.txt track*.tck ./raw/
+#	echo "complete"
+#	exit 0
+#else
+#	echo "tracking failed"
+#	exit 1
+#fi
